export const GET_ALL_RECIPE_REQUEST = "GET_ALL_RECIPE_REQUEST"
export const GET_ALL_RECIPE_SUCCESS = "GET_ALL_RECIPE_SUCCESS"
export const GET_ALL_RECIPE_FAIL = "GET_ALL_RECIPE_FAIL"

export const ADD_RECIPE_REQUEST = "ADD_RECIPE_REQUEST"
export const ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS"
export const ADD_RECIPE_FAIL = "ADD_RECIPE_FAIL"

export const UPDATE_RECIPE_REQUEST = "UPDATE_RECIPE_REQUEST"
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS"
export const UPDATE_RECIPE_FAIL = "UPDATE_RECIPE_FAIL"

export const DELETE_RECIPE_REQUEST = "DELETE_RECIPE_REQUEST"
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS"
export const DELETE_RECIPE_FAIL = "DELETE_RECIPE_FAIL"


export const ADD_INGRIDIENTS_REQUEST = "ADD_INGRIDIENTS_REQUEST"
export const ADD_INGRIDIENTS_SUCCESS = "ADD_INGRIDIENTS_SUCCESS"
export const ADD_INGRIDIENTS_FAIL = "ADD_INGRIDIENTS_FAIL"