export const REGISTERED_USER_REQUEST = "REGISTERED_USER_REQUEST"
export const REGISTERED_USER_SUCCESS = "REGISTERED_USER_SUCCESS"
export const REGISTERED_USER_FAIL = "REGISTERED_USER_FAIL"

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"

export const USER_LOGOUT = "ADMIN_LOGOUT"